/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-02-26 15:47:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.produto;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class form_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Cadastro de Produto</title>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("            background: linear-gradient(135deg, #1e3c72, #2a5298);\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 500px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card {\r\n");
      out.write("            background: white;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 6px 18px rgba(0,0,0,0.15);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 25px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 18px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        label {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            margin-top: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input:focus {\r\n");
      out.write("            outline: none;\r\n");
      out.write("            border-color: #2a5298;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .error {\r\n");
      out.write("            color: red;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            margin-top: 4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            background-color: #2a5298;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button:hover {\r\n");
      out.write("            background-color: #1e3c72;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-secondary {\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            background-color: #555;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-secondary:hover {\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <h2>📦 Cadastro de Produto</h2>\r\n");
      out.write("\r\n");
      out.write("        <form id=\"produtoForm\" \r\n");
      out.write("              action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/produtos\" \r\n");
      out.write("              method=\"post\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>Descrição:</label>\r\n");
      out.write("                <input type=\"text\" name=\"descricao\" id=\"descricao\">\r\n");
      out.write("                <div class=\"error\" id=\"erroDescricao\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>Valor:</label>\r\n");
      out.write("                <input type=\"number\" name=\"valor\" step=\"0.01\" min=\"0\" id=\"valor\" required>\r\n");
      out.write("                <div class=\"error\" id=\"erroValor\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>Quantidade:</label>\r\n");
      out.write("                <input type=\"number\" name=\"qtd\" id=\"qtd\"  min=\"0\" step=\"1\">\r\n");
      out.write("                <div class=\"error\" id=\"erroQtd\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>Data Cadastro:</label>\r\n");
      out.write("                <input type=\"date\" name=\"dataCadastro\" id=\"dataCadastro\">\r\n");
      out.write("                <div class=\"error\" id=\"erroData\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\">Salvar</button>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/produtos\">\r\n");
      out.write("                <button type=\"button\" class=\"btn-secondary\">Voltar</button>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("\r\n");
      out.write("    const valorInput = document.getElementById(\"valor\");\r\n");
      out.write("    const form = document.getElementById(\"produtoForm\");\r\n");
      out.write("\r\n");
      out.write("    valorInput.addEventListener(\"input\", function (e) {\r\n");
      out.write("        let v = e.target.value;\r\n");
      out.write("\r\n");
      out.write("        v = v.replace(/\\D/g, \"\");\r\n");
      out.write("\r\n");
      out.write("        if (v.length === 0) {\r\n");
      out.write("            e.target.value = \"0.00\";\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        let numero = parseInt(v);\r\n");
      out.write("        let formatado = (numero / 100).toFixed(2);\r\n");
      out.write("\r\n");
      out.write("        e.target.value = formatado;\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    valorInput.addEventListener(\"focus\", function (e) {\r\n");
      out.write("        if (e.target.value === \"\") {\r\n");
      out.write("            e.target.value = \"0.00\";\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    form.addEventListener(\"submit\", function(e) {\r\n");
      out.write("\r\n");
      out.write("        let valido = true;\r\n");
      out.write("\r\n");
      out.write("        document.querySelectorAll(\".error\").forEach(el => el.innerText = \"\");\r\n");
      out.write("\r\n");
      out.write("        let descricao = document.getElementById(\"descricao\").value.trim();\r\n");
      out.write("        let valor = parseFloat(valorInput.value);\r\n");
      out.write("        let qtd = parseInt(document.getElementById(\"qtd\").value);\r\n");
      out.write("        let data = document.getElementById(\"dataCadastro\").value;\r\n");
      out.write("\r\n");
      out.write("        let hoje = new Date().toISOString().split(\"T\")[0];\r\n");
      out.write("\r\n");
      out.write("        if (descricao === \"\") {\r\n");
      out.write("            document.getElementById(\"erroDescricao\").innerText = \"Descrição é obrigatória.\";\r\n");
      out.write("            valido = false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (isNaN(valor) || valor <= 0) {\r\n");
      out.write("            document.getElementById(\"erroValor\").innerText = \"Valor deve ser maior que zero.\";\r\n");
      out.write("            valido = false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (isNaN(qtd) || qtd < 0) {\r\n");
      out.write("            document.getElementById(\"erroQtd\").innerText = \"Quantidade não pode ser negativa.\";\r\n");
      out.write("            valido = false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (data === \"\") {\r\n");
      out.write("            document.getElementById(\"erroData\").innerText = \"Data é obrigatória.\";\r\n");
      out.write("            valido = false;\r\n");
      out.write("        } else if (data > hoje) {\r\n");
      out.write("            document.getElementById(\"erroData\").innerText = \"Data não pode ser futura.\";\r\n");
      out.write("            valido = false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (!valido) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
